sudo: required
services:
  - docker
language: bash
script:
  # Create config
  - echo IMG_NAME='Raspbian' >config
  # Build only Raspbian LITE
  - touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
  - rm stage5/EXPORT*
  # Build with Docker
  - ./build-docker.sh
  # List artifacts
  - ls -l deploy/
branches:
  only:
    - my
    - stretch
    - /^v\d.*$/
deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_TOKEN}
  file:
    - deploy/image_$(date +%Y-%m-%d)-Raspbian-lite.zip
  on:
    tags: true
    repo: StefanScherer/pi-gen

